image: gcc:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
services:
  - docker:18.09.7-dind

stages:
  - sync
  - build

include:
  - local: 'configs/sync.yaml'
  - local: 'configs/build.yaml'
