image: gcc:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
services:
  - docker:18.09.7-dind

stages:
  - sync
  - build

sync_upstream:
  stage: sync
  script:
    - git remote add upstream https://github.com/cosmic-otter/hello.git
    - git fetch upsteam
    - git merge upsteam/main
  schedule:
    - cron: "/15 * * * *"

build:
  tags: [ local-gitlab-dev ]
  stage: build
  script:
    - make all
  artifacts:
    paths:
      - hello
