image: gcc:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
services:
  - docker:18.09.7-dind


stages:
  - build
  - package

build:
  tags: [ local-gitlab-dev ]
  stage: build
  script:
    - make all
  artifacts:
    paths:
      - hello
