sync:
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  tags: [ local-gitlab-dev ]
  stage: sync
  rules:
    - if: '$TARGETTASKNAME== "sync-task"'
  script:
    - git config --global user.email "srv@hrl.internal"
    - git config --global user.name "Service Account"
    - git branch
    # - echo $SSH_KEY
    - git switch master
    - git remote add upstream https://github.com/cosmic-otter/hello.git || true
    - git fetch upstream
    - git pull --no-edit --no-ff upstream main -X theirs
    - git remote -v
    - git branch
    - git branch --set-upstream-to origin/master || true
    - |
      if ! git diff --quiet origin/master --name-only; then \
        git push -u origin master; \
      fi
